spring:
  application:
    name: DEMO-SERVICE
 
eureka:
  instance:
    appname: MY-DEMO-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8086 