spring:
  application:
    name: CLIENT-SERVICE

eureka:
  instance:
    appname: CLIENT-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082